### ISSUE TITLE
View mock-up

### ISSUE THREAD

**Issue by Narekushia** [HE-Arc/TimeLife#1]
Mock-up of the view to do : 
  - [x] Map view
  - [x] Timeline view
  - [x] Landing page view (when connected)
  - [x] Edit timeline item (image) view
  - [x] Create timeline item (image) view
  - [x] User profile view

**Comment by cocofaivre** [comment]
Schema BDD v0.1
![schema](https://user-images.githubusercontent.com/15803484/135474016-9583e8fa-6326-46d4-803d-cc12b0632088.PNG)

**Comment by Narekushia** [comment]
Done ! They are in the "Spécifications détaillées" page : <https://github.com/HE-Arc/TimeLife/wiki/Spécifications-détaillées>
